config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "forum_threads#index"

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
    resource :like, module: :forum_threads
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  forum_thread_id :integer
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ForumPost < ApplicationRecord
  belongs_to :forum_thread, inverse_of: :forum_posts
  belongs_to :user

  validates :body, presence: true
  def send_notifications!
    # Identify all the unique users in this thread
    users = forum_thread.users.uniq - [user]
    # Send an email to each of those users
    users.each do |user|
      NotificationMailer.forum_post_notification(user, self).deliver_later
    end    
  end
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  subject    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ForumThread < ApplicationRecord
  belongs_to :user
  has_many :forum_posts, inverse_of: :forum_thread
  has_many :users, through: :forum_posts
  has_many :likes

  accepts_nested_attributes_for :forum_posts,
                                reject_if: proc { |attributes| attributes[:body].blank? },
                                allow_destroy: true

  validates :subject, presence: true
  validates_associated :forum_posts


  

end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  forum_thread_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Like < ApplicationRecord
  belongs_to :user, inverse_of: :likes
  belongs_to :forum_thread, inverse_of: :likes
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :forum_threads
  has_many :forum_posts
  has_many :likes

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def name
    "#{first_name} #{last_name}"
  end

  def likes?(forum_thread)
    forum_thread.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread


  def create
    @forum_post = @forum_thread.forum_posts.new forum_post_params
    @forum_post.user = current_user

    if @forum_post.save
      @forum_post.send_notifications!
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}"), notice: "Successfully posted!"
    else
      redirect_to @forum_thread, alert: "Unable to save your post"
    end 
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads/likes_controller.rb
class ForumThreads::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread
  
  def create
    @forum_thread.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @forum_thread}
      format.js
    end
  end

  def destroy
    @forum_thread.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @forum_thread}
      format.js
    end
    
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]
  def index
    @q = ForumThread.search(params[:q])
    @forum_threads = @q.result(distinct:true)
  end

  def show
    @forum_post = ForumPost.new
  end

  def new
   @forum_thread = ForumThread.new
   @forum_thread.forum_posts.new
  end

  def create
    @forum_thread = current_user.forum_threads.new(forum_thread_params)
    
    @forum_thread.forum_posts.first.user_id = current_user.id
    if @forum_thread.save
      redirect_to @forum_thread
    else
      render 'new'
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:id, :body, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_posts/_forum_post.html.erb
<%= div_for forum_post do %>  
  <p class="text-muted">Posted by <%= forum_post.user.name%> on <%= local_time forum_post.created_at %></p>
  <p><%= simple_format(forum_post.body) %></p>
<% end %>

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control"%>
  </div>

  <%= f.fields_for :forum_posts do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Add a comment", rows: 10, class:"form-control"%>
    </div>
  <% end -%>

  <div class="form-group">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end -%>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
  <h3><%= forum_thread.subject %></h3>  
<% end %>
<p><%= forum_thread.likes.count%> Likes</p>
<p><%= forum_thread.forum_posts.count%> Posts</p>

app/views/forum_threads/_likes.html.erb
<% if user_signed_in? && current_user.likes?(forum_thread) %>
  <%= link_to forum_thread_like_path(forum_thread), method: :delete, remote: true do %>
    <span class="glyphicon glyphicon-thumbs-up"></span>
  <% end -%>
<% else %>
  <%= link_to forum_thread_like_path(forum_thread), method: :post, remote: true do %>
    <span class="glyphicon glyphicon-thumbs-down"></span>
  <% end -%>
<% end -%>

<%= @forum_thread.likes.count%>
<% @forum_thread.likes.each do |like| %>
  <%= image_tag like.user.avatar.url, width: 20, :style => "border-radius: 30%" %>  
<% end -%>

app/views/forum_threads/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "New Thread", new_forum_thread_path, class: "btn btn-success" %>
  </div>

  <div class="pull-right" style="margin-right: 10px">
    <%= search_form_for @q, html: { class: "form-inline"} do |f| %>
      <%= f.search_field :subject_or_forum_posts_body_cont, placeholder: "Search...", class: "form-control" %>
    <% end -%>
  </div>
  

  <h1 class="page-header">Forum Threads</h1>
  <%= render @forum_threads %>
</div>

app/views/forum_threads/likes/create.js.erb
$("#forum_thread_<%= @forum_thread.id %>_likes").html("<%=j render partial: "forum_threads/likes", locals: {forum_thread: @forum_thread} %>");

app/views/forum_threads/likes/destroy.js.erb
$("#forum_thread_<%= @forum_thread.id %>_likes").html("<%=j render partial: "forum_threads/likes", locals: {forum_thread: @forum_thread} %>");

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render "form" %>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>  
  
  
  <%= render @forum_thread.forum_posts %>
  <div id="forum_thread_<%= @forum_thread.id %>_likes">
    <%= render partial: "likes", locals: {forum_thread: @forum_thread} %>
  </div>

  <hr />
  <%= render partial: "forum_posts/form" %>
      
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gorailsforum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <div class="container">
      <%= flash.notice %>
      <%= flash.alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header class="navbar <%= content_for?(:navbar_style) ? yield(:navbar_style) : "navbar-default" %> navbar-static-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        Forum
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Threads", forum_threads_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>